{ inputs, ... }:{

  flake.nixosConfigurations.update-system = inputs.nixpkgs.lib.nixosSystem {
    modules = [ (inputs.import-tree [
      inputs.disko.flakeModules.default
      inputs.disko.nixosModules.default # disko lib
      inputs.self.diskoConfigurations.update-system # disko config
      inputs.agenix.nixosModules.default # agenix lib
      inputs.self.nixosModules.update-system # nixos config
      inputs.self.nixosModules.depnix # depnix args

      # Conditional import checks if hardware-config exists or if we return empty config (just to pass the evaluator and allow nixos-anywhere to generate the config)
      (if (builtins.pathExists ./hardware-config.nix) then ./hardware-config.nix else {})
    ] ) ];
  };

  flake.nixosModules.update-system = { config, lib, pkgs, ... }: {

    depnix.deploy = {
      # Directories are relative to the git repo root
      user = "root";
      host = "10.0.10.140";
      encryptionKey = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILS702QCxlr2wTXjZDaJ0IiO5NKkYMAgN4Ei+YbS19sF"; # Encrypts the ssh_host_keys
      decryptionKeyFile = "~/.ssh/id_ed25519";                                                            # Decrypts the ssh_host_keys
      sshHostKeyDir = "./modules/update-system";                                                            # directory to store the ssh_host_keys in age encrypted tar.gz
      hardwareConfigFile = "./modules/update-system/hardware-config.nix";                                   # path to hardware config file generated by nixos-anywhere
    };

    depnix.rebuild = {
      user = "kyle";
      host = "10.0.10.140";
      id = "~/.ssh/id_ed25519";
      useRemoteSudo = true;
    };

    depnix.ssh = {
      user = "kyle";
      host = "10.0.10.140";
      id = "~/.ssh/id_ed25519";
    };

    system.stateVersion = "25.05";

    environment.systemPackages = [
      pkgs.neovim
    ];

    nixpkgs.config.allowUnfree = true;
    nix.settings.experimental-features = [ "nix-command" "flakes" ];
    system.configurationRevision = if inputs.self ? rev then inputs.self.rev else inputs.self.dirtyRev;

    # Networking
    networking.hostName = "update-system";
    networking.networkmanager = { enable = true; };

    # time/language
    time.timeZone = "America/Toronto";
    i18n.defaultLocale = "en_CA.UTF-8";

    # useful
    security.sudo.execWheelOnly = true;
    security.sudo.wheelNeedsPassword = false;

    # user
    users.groups.kyle = { };
    users.users.kyle = {
      isNormalUser = true;
      group = "kyle";
      description = "kyle";
      shell = pkgs.bashInteractive;
      initialPassword = "testpassword";
      openssh.authorizedKeys.keys = [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILS702QCxlr2wTXjZDaJ0IiO5NKkYMAgN4Ei+YbS19sF kyle@sorin" ];
      extraGroups = [ "networkmanager" "wheel" ];
    };
    services.openssh = {
      enable = true;
      openFirewall = true;
    };

    # boot
    boot.loader.systemd-boot.enable = true;
    boot.loader.systemd-boot.configurationLimit = 10;
    boot.loader.efi.canTouchEfiVariables = true;
    boot.kernelPackages = pkgs.linuxPackages;
    security.rtkit.enable = true;

    # minimum build requirements
    nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  };

  flake.diskoConfigurations.update-system.disko.devices = {
    disk = {
      main = {
        device = "/dev/sda";
        type = "disk";
        content = {
          type = "gpt";
          partitions = {
            ESP = {
              type = "EF00";
              size = "1G";
              content = {
                type = "filesystem";
                format = "vfat";
                mountpoint = "/boot";
                mountOptions = [ "umask=0077" ];
              };
            };
            root = {
              size = "100%";
              content = {
                type = "filesystem";
                format = "ext4";
                mountpoint = "/";
              };
            };
            swap = {
              size = "4G";
              content = {
                type = "swap";
                discardPolicy = "both";
              };
            };
          };
        };
      };
    };
  };
}
