#!/usr/bin/env bash

###############################################################
### Initial Variables #########################################
###############################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CLEAR='\033[0m'

###############################################################
### Help Dialog ###############################################
###############################################################

# Normalize
set -euo pipefail
exe_root=$(pwd) # Where we are executing from
git_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd) # where we will be for most things

# shellcheck
show_help() {  #!TODO: change project name
  echo -e "
$(printf '=%.0s' $(seq 1 $(tput cols)))
 ${GREEN}
 ${GREEN}
 ${GREEN} placeholder
 ${GREEN}
 ${GREEN}
 ${GREEN}  ${CLEAR}
$(printf '=%.0s' $(seq 1 $(tput cols)))
  Usage:${RED} $0 ${GREEN}<nix-file> [subcommand] [-d|--debug] [-h|--help] [-k|--key path] [-c|--command \"echo \'hello'\" ] [-o|--options \"\"]
      <nix-file> This is the inventory $0 will use

  Options:
 ${RED}      mode                ${GREEN}Specifies the operation you want to take.
 ${RED}
 ${RED}                          ${GREEN}init      =  Generate a template of <nix_file> to populate.
 ${RED}                          ${GREEN}genkey    =  Create new ssh keys to bootstrap a server
 ${RED}                          ${GREEN}rekey     =  Decrypt and re-key the secrets/sshkeys
 ${RED}                          ${GREEN}deploy    =  Run nixos-anywhere and deploy the server, destroying any and all data there.
 ${RED}                          ${GREEN}test      =  Run nixos-rebuild test and rebuild the server
 ${RED}                          ${GREEN}boot      =  Run nixos-rebuild boot on the server
 ${RED}                          ${GREEN}switch    =  Run nixos-rebuild switch and rebuild the server
 ${RED}                          ${GREEN}ssh       =  Run arbitrary commands on remote servers
 ${RED}
 ${RED}   -c | --command         ${GREEN}when using ssh mode, specify a command to run on the servers
 ${RED}                          ${GREEN}this option uses ssher: https://github.com/kr-nn/ssher
 ${RED}
 ${RED}   -o | --options         ${GREEN}Add arbitrary options to nixos-rebuild/nixos-anywhere/ssher
 ${RED}
 ${RED}   -k | --key             ${GREEN}Path to current key when using rekey mode
 ${RED}
 ${RED}   -d | --debug           ${GREEN}Explain what we are going to do instead of doing it
 ${RED}
 $(printf '=%.0s' $(seq 1 $(tput cols)))
 ${RED}
 ${RED}      nix options:
 ${RED}        flakename:        Str that matches flake output (must be a Nixos Configuration):
 ${RED}          deploy:           Attrset of below:
 ${RED}            .hostname:        Str of ssh host: root@hostname
 ${RED}            .secret:          Path to the private age key for decrypting the ssh host keys on deployment
 ${RED}            .keydir:          Path to where we store the encrypted ssh host keys
 ${RED}          rebuild:          List of attrsets that contain host information after deployment
 ${RED}            .hostname:        Str of ssh host: user@hostname
 ${RED}            .secret:          Path to the private ssh key for authenticating to the server
 ${RED}
 ${RED}      Example below:
 ${RED}      {
 ${RED}        flakename = {
 ${RED}          deploy = {
 ${RED}            username = "root";
 ${RED}            hostname = "10.0.10.120";
 ${RED}            secret = /home/$USER/.ssh/id_ed25519;
 ${RED}            keydir = ./hosts/hostname/secrets;
 ${RED}          };
 ${RED}          rebuild = {
 ${RED}            username = "user";
 ${RED}            hostname = "10.0.10.120";
 ${RED}            secret = /home/$USER/.ssh/id_ed25519;
 ${RED}          };
 ${RED}        };
 ${RED}      }
$(printf '=%.0s' $(seq 1 $(tput cols)))" | less
}

dryrun() {
  local action="$1"
  local flake="$2"
  local hostname="$3"
  local secret="$4"
  local key="$5"
  local oldkey="$6"
  case $action in
    "ssh") drysshrun "$hostname" "$sshcmd" "$secret" ;;
    "genkey") drygenerate_keys "$flake" "$hostname" "$secret" "$key" ;;
    "rekey") dryrekey_keys "$flake" "$secret" "$key" "$oldkey" ;;
    "deploy") drydeploy "$flake" "$hostname" "$secret" "$key" ;;
    "switch"|"test"|"boot") dryrebuild "$flake" "$hostname" "$action" ;;
  esac
}

init() {
  [[ ! -f "$exe_root/$nix_file" ]] || (read -p "This file exists do you want to overwrite it? (y/n): " reply && [[ $reply =~ ^[Yy]$ ]]) || exit 0
  cat <<EOF > $nix_file
    {
      flakename = {
        deploy = {
          username = "root";
          host = "10.0.10.120";
          secret = /home/$USER/.ssh/id_ed25519;
          keydir = ./hosts/hostname/secrets;
        };
        rebuild = {
          username = "user";
          host = "10.0.10.120";
          secret = /home/$USER/.ssh/id_ed25519;
        };
      };
    }
EOF

  echo "Created $nix_file"
  exit 0
}

generate_keys() {
  local flake="$1" # Needs to be in each function because we don't want to share a directory with multiple servers
  local hostname="$2"
  local secret="$3"
  local key="$4" # where the ssh_host_keys will go
  local temp=$(mktemp -d)
  local host="${hostname#*@}"
  public_key=$(age-keygen -y $secret)
  echo "Generating and encrypting SSH keys for $host..."

  install -d -m755 $temp/etc/ssh
  ssh-keygen -Af $temp
  echo "Generated keys ..."
  [ -d $key ] || mkdir -p $key
  tar -cz -C $temp etc | age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age

  echo "Keys encrypted and saved as ${key}/${flake}_sshkeys.tgz.age"
  echo ""
  echo "You can use these keys for decrypting secrets with agenix/sopsnix"
  echo "Use the host key to sign all secrets:"
  echo "$(cat $temp/etc/ssh/ssh_host_ed25519_key.pub)"
  echo ""
  echo "Cleaning $temp ..."
  rm -rf $temp
  echo "Done generating $flake keys"
}

drygenerate_keys() { #!TODO: merge to standard
  local flake="$1" # Needs to be in each function because we don't want to share a directory with multiple servers
  local hostname="$2"
  local secret="$3"
  local key="$4" # where the ssh_host_keys will go
  local temp=$(echo "(mktemp -d)")
  local host="${hostname#*@}"
  public_key=$(echo "(age-keygen -y $secret)")
  echo "Generating and encrypting SSH keys for $host..."

  echo install -d -m755 $temp/etc/ssh
  echo ssh-keygen -Af $temp
  echo "Generated keys ..."
  echo "[ -d $key ] || mkdir -p $key"
  echo "tar -cz -C $temp etc | age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age"

  echo "Keys encrypted and saved as ${key}/${flake}_sshkeys.tgz.age"
  echo ""
  echo "You can use these keys for decrypting secrets with agenix/sopsnix"
  echo "Use the host key to sign all secrets:"
  echo "cat $temp/etc/ssh/ssh_host_ed25519_key.pub)"
  echo ""
  echo "Cleaning $temp ..."
  echo "rm -rf $temp"
  echo "Done generating $flake keys"
}

rekey_keys() {
  local flake="$1"
  local secret="$2"
  local key="$3" # where the ssh_host_keys will go
  local oldkey="$4" # -k defines the old key to re-key with
  local temp=$(mktemp -d)
  public_key=$(age-keygen -y $secret)
  echo "de-crypting SSH keys with old key for $hostname..."
  age -d -i $oldkey ${key}/${flake}_sshkeys.tgz.age | tar -xz -C "$temp"
  echo "re-encrypting SSH keys with new key for $hostname..."
  tar -cz -C $temp etc |age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age
  echo ""
  echo "Cleaning $temp ..."
  rm -rf $temp
  echo "Done rekeying $flake keys"
}
dryrekey_keys() { #!TODO: merge to standard
  local flake="$1"
  local secret="$2"
  local key="$3" # where the ssh_host_keys will go
  local oldkey="$4" # -k defines the old key to re-key with
  local temp=$(echo "(mktemp -d)")
  public_key=$(echo "(age-keygen -y $secret)")
  echo "de-crypting SSH keys with old key for $hostname..."
  echo "age -d -i $oldkey ${key}/${flake}_sshkeys.tgz.age | tar -xz -C \"$temp\""
  echo "re-encrypting SSH keys with new key for $hostname..."
  echo "tar -cz -C $temp etc |age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age"
  echo ""
  echo "Cleaning $temp ..."
  echo "rm -rf $temp"
  echo "Done rekeying $flake keys"
}

deploy() {
  local flake="$1"
  local hostname="$2"
  local secret="$3"
  local key="$4" # where the ssh_host_keys are located
  local temp=$(mktemp -d)

  echo "Deploying $flake to $hostname..."
  mkdir -p "$temp"
  age -d -i $secret ${key}/${flake}_sshkeys.tgz.age | tar -xz -C "$temp"

  # Run nixos-anywhere
  nixos-anywhere ${options} -f .\#$flake --target-host $hostname --extra-files $temp
  echo "Cleaning $temp ..."
  rm -rf $temp
  echo "Finished deploying $flake"
}
drydeploy() { #!TODO: merge to standard
  local flake="$1"
  local hostname="$2"
  local secret="$3"
  local key="$4" # where the ssh_host_keys are located
  local temp=$(echo "(mktemp -d)")

  echo "Deploying $flake to $hostname..."
  echo mkdir -p "$temp"
  echo "age -d -i $secret ${key}/${flake}_sshkeys.tgz.age | tar -xz -C \"$temp\""

  # Run nixos-anywhere
  echo nixos-anywhere ${options} -f .\#$flake --target-host $hostname --extra-files $temp
  echo "Cleaning $temp ..."
  echo rm -rf $temp
  echo "Finished deploying $flake"
}

sshrun() {
  local hostname="$1"
  local sshcmd="$2"
  local secret="$3"
  ssh $hostname -i $secret $sshcmd
}
drysshrun() { #!TODO: merge to standard
  local hostname="$1"
  local sshcmd="$2"
  local secret="$3"
  echo "ssh $hostname -i $secret $sshcmd"
}

rebuild() {
  local flake="$1"
  local hostname="$2"
  local action="$3"
  local user="${hostname%@*}"
  [[ ! "$user" == "root" ]] && { sudocmd=" --use-remote-sudo"; } || { sudocmd=""; }
  echo "Rebuilding $flake to $hostname..."
  nixos-rebuild "$action" --flake .\#"$flake" "${options}" --target-host "$hostname" "$sudocmd"
}
dryrebuild() { # TODO: merge to standard
  local flake="$1"
  local hostname="$2"
  local action="$3"
  local user="${hostname%@*}"
  [[ ! "$user" == "root" ]] && { sudocmd=" --use-remote-sudo"; } || { sudocmd=""; }
  echo "Rebuilding $flake to $hostname..."
  echo nixos-rebuild "$action" --flake .\#"$flake" "${options}"--target-host "$hostname" "$sudocmd"
}

main() {

  ## Help Dialog
  #for arg in "$@"; do
  #  if [[ "$arg" == "-h" ]]; then
  #    show_help && exit 0
  #  fi
  #done

  #if [[ "$#" -lt 2 ]]; then # TODO: Remove this
  #    echo "There is not enough arguments. Use -h to read help" && exit 1
  #fi

  nix_file="$1"
  action="$2"
  dry=0
  key=0
  oldkey=0
  jsonroot=0
  sshcmd=0
  options=""
  shift 2

  # We only want to move on when file exists or we're creating one
  [ -f "$exe_root/$nix_file" || $action == "init" ] || { echo "File: $nix_file doesn't exist" && exit 1; }
  #[[ $action == "init" ]] || exit 1

  while getopts ":hdo:k:c:" opt; do
    case $opt in
      h) show_help && exit 0 ;;
      d) original_action=$action && action="dryrun" ;;
      o) options="$OPTARG" ;;
      k) oldkey="$OPTARG" ;;
      c) sshcmd="$OPTARG" ;;
      :) show_help && exit 1 ;;
      \?) show_help && exit 1 ;;
    esac
  done

  [[ $action == "ssh" && $sshcmd == 0 ]] && (echo "No command given for ssh mode" && exit 1)

  case $action in
    "init") init ;;
    "dryrun") [[ $original_action == "init" ]] && dryinit || [[ "$original_action" =~ ^(genkey|rekey|deploy)$ ]] && jsonroot="deploy" || jsonroot="rebuild" ;;
    "genkey"|"rekey"|"deploy") jsonroot="deploy" ;;
    "switch"|"test"|"boot"|"ssh") jsonroot="rebuild" ;;
    *) echo "Invalid action: $action" && echo "" && show_help && exit 1 ;;
  esac

  server_keys=$( nix eval --file "$nix_file" --json | jq keys )

  echo "$server_configs" | jq -c '.[]' | while read -r jsonroot; do

    hostname=$(echo "$jsonroot" | jq -r '.hostname')
    secret=$(echo "$jsonroot" | jq -r '.secret')
    key=$(echo "$jsonroot" | jq -r '.keydir')

    echo "performing $action on $flake ==================================="
    case $action in
      "ssh") sshrun "$hostname" "$sshcmd" "$secret" ;;
      "dryrun") dryrun "$original_action" "$flake" "$hostname" "$secret" "$key" "$oldkey" ;;
      "genkey") generate_keys "$flake" "$hostname" "$secret" "$key" ;;
      "rekey") rekey_keys "$flake" "$secret" "$key" "$oldkey" ;;
      "deploy") deploy "$flake" "$hostname" "$secret" "$key" ;;
      "switch"|"test"|"boot") rebuild "$flake" "$hostname" "$action" ;;
      *) echo "Invalid action: $action" && echo "" && show_help && exit 1 ;;
    esac
    echo ""
    echo "================================================================"

  done
}

main "$@"
