#!/usr/bin/env bash

###############################################################
### Initial Variables #########################################
###############################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
CLEAR='\033[0m'

###############################################################
### Help Dialog ###############################################
###############################################################

# Normalize
set -eo pipefail
exe_root=$(pwd) # Where we are executing from
git_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd) # where we will be for most things

show_help() {
  echo -e "
$(printf '=%.0s' $(seq 1 $(tput cols)))
 ${GREEN}
          
          placeholder
          
          
          
 ${CLEAR}
$(printf '=%.0s' $(seq 1 $(tput cols)))
Usage:${RED} $0 ${GREEN}mode [name] [-h|--help]

  Options:
 ${RED}      [mode]           ${GREEN}  Specifies the operation you want to take.
 ${RED}
 ${RED}                       ${GREEN}    ls        =  List the nixosConfigurations in your flake and show their parameters.
 ${RED}                       ${GREEN}    genkey    =  Create new ssh keys to bootstrap a server
 ${RED}                       ${GREEN}    rekey     =  Decrypt and re-key the secrets/sshkeys
 ${RED}                       ${GREEN}    deploy    =  Run nixos-anywhere and deploy the server, destroying any and all data there.
 ${RED}                       ${GREEN}    test      =  Run nixos-rebuild test
 ${RED}                       ${GREEN}    boot      =  Run nixos-rebuild boot
 ${RED}                       ${GREEN}    switch    =  Run nixos-rebuild switch
 ${RED}                       ${GREEN}    ssh       =  Run arbitrary commands on remote servers
 ${RED}
 ${RED}      [name]           ${GREEN}  The name of the nixosConfiguration you want to work with
 ${RED}
 ${RED}   -h | --help         ${GREEN}  Display help dialog (You can specify the mode as well)
 ${RED}
$(printf '=%.0s' $(seq 1 $(tput cols)))" | less

}

###############################################################
### helper funcs ##############################################
###############################################################

split_args() {
  local consuming_flags=( "-k" "-c" )

  pos_args=()
  flag_args=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -k|-c)
        flag_args+=("$1" "$2")
        shift 2
        ;;
      -*)
        flag_args+=("$1")
        shift
        ;;
      *)
        pos_args+=("$1")
        shift
        ;;
    esac
  done
}

ls-help() { echo -e "Usage:${RED} depnix ${GREEN}ls [name] [-h|--help]"
}
ls-mode() {

  set -- "${flag_args[@]}"

  while getopts ":h" opt; do
    case $opt in
      h) ls-help && exit 0 ;;
      *) : ;;
    esac
  done

  set -- "${pos_args[@]}" && shift

  nixosNames=$(nix eval .#nixosConfigurations --apply 'builtins.attrNames')
  if [ $# -lt 1 ]; then
    set -- "$(nix eval .#nixosConfigurations --apply 'builtins.attrNames'|jq -r '.[]')"
  fi
  while [ $# -gt 0 ]; do
    if "$(echo "$nixosNames" | jq "IN(.[]; \"$1\")")"; then
      Conf=$(nix eval --json ".#nixosConfigurations.$1.config.depnix" |jq)
      echo "nixosConfiguration.$1.depnix = $Conf"
    else
      echo "$1 is not a valid nixosConfiguration"
    fi
    shift
  done

}

main() {
  split_args "$@"

  set -- "${pos_args[@]}"
#  set -- "${flag_args[@]}"

  mode=$1

  case "$mode" in
    "ls")
      shift
      ls-mode "$@" && exit 0
    ;;
    "genkey")
      shift
      genkey-mode "$@" && exit 0
    ;;
    "rekey")
      shift
      rekey-mode "$@" && exit 0
    ;;
    "deploy")
      shift
      deploy-mode "$@" && exit 0
    ;;
    "test")
      shift
      test-mode "$@" && exit 0
    ;;
    "boot")
      shift
      boot-mode "$@" && exit 0
    ;;
    "switch")
      shift
      switch-mode "$@" && exit 0
    ;;
    "ssh")
      shift
      ssh-mode "$@" && exit 0
    ;;
    *)
      show_help && exit 1;
    ;;

  esac
}

main "$@"

#  while getopts ":hk:c:" opt; do
#    case $opt in
#      k) oldkey="$OPTARG" ;;
#      c) sshcmd="$OPTARG" ;;
#      :) show_help && exit 1 ;;
#      \?) show_help && exit 1 ;;
#    esac
#  done
#
#  [[ $action == "ssh" && $sshcmd == 0 ]] && (echo "No command given for ssh mode" && exit 1)
#
#  case $action in
#    "init") init ;;
#    "dryrun") [[ $original_action == "init" ]] && dryinit || [[ "$original_action" =~ ^(genkey|rekey|deploy)$ ]] && jsonroot="deploy" || jsonroot="rebuild" ;;
#    "genkey"|"rekey"|"deploy") jsonroot="deploy" ;;
#    "switch"|"test"|"boot"|"ssh") jsonroot="rebuild" ;;
#    *) echo "Invalid action: $action" && echo "" && show_help && exit 1 ;;
#  esac
#
#  servers=$(nix eval --json '.#nixosConfigurations' --apply 'builtins.attrNames')
#  server_keys=$( nix eval --file "$nix_file" --json | jq keys )
#
#  echo "$server_configs" | jq -c '.[]' | while read -r jsonroot; do
#
#    hostname=$(echo "$jsonroot" | jq -r '.hostname')
#    secret=$(echo "$jsonroot" | jq -r '.secret')
#    key=$(echo "$jsonroot" | jq -r '.keydir')
#
#    echo "performing $action on $flake ==================================="
#    case $action in
#      "ssh") sshrun "$hostname" "$sshcmd" "$secret" ;;
#      "dryrun") dryrun "$original_action" "$flake" "$hostname" "$secret" "$key" "$oldkey" ;;
#      "genkey") generate_keys "$flake" "$hostname" "$secret" "$key" ;;
#      "rekey") rekey_keys "$flake" "$secret" "$key" "$oldkey" ;;
#      "deploy") deploy "$flake" "$hostname" "$secret" "$key" ;;
#      "switch"|"test"|"boot") rebuild "$flake" "$hostname" "$action" ;;
#      *) echo "Invalid action: $action" && echo "" && show_help && exit 1 ;;
#    esac
#    echo ""
#    echo "================================================================"
#
#  done
#}
#
#main "$@"
 #${RED}                       ${GREEN}    ls        =  List the nixosConfigurations in your flake and show their parameters.
 #${RED}                       ${GREEN}    genkey    =  Create new ssh keys to bootstrap a server
 #${RED}                       ${GREEN}    rekey     =  Decrypt and re-key the secrets/sshkeys
 #${RED}                       ${GREEN}    deploy    =  Run nixos-anywhere and deploy the server, destroying any and all data there.
 #${RED}                       ${GREEN}    test      =  Run nixos-rebuild test
 #${RED}                       ${GREEN}    boot      =  Run nixos-rebuild boot
 #${RED}                       ${GREEN}    switch    =  Run nixos-rebuild switch
 #${RED}                       ${GREEN}    ssh       =  Run arbitrary commands on remote servers
# ${RED}   -c | --command      ${GREEN}  when using ssh mode, specify a command to run on the servers
# ${RED}                       ${GREEN}  this option uses ssher: https://github.com/kr-nn/ssher
# ${RED}
# ${RED}   -o | --options      ${GREEN}  Add arbitrary options to nixos-rebuild/nixos-anywhere/ssher
# ${RED}
# ${RED}   -k | --key          ${GREEN}  Path to current key when using rekey mode
# ${RED}
# ${RED}   -d | --debug        ${GREEN}  Explain what we are going to do instead of doing it
# ${RED}

#generate_keys() {
#  local flake="$1" # Needs to be in each function because we don't want to share a directory with multiple servers
#  local hostname="$2"
#  local secret="$3"
#  local key="$4" # where the ssh_host_keys will go
#  local temp=$(mktemp -d)
#  local host="${hostname#*@}"
#  public_key=$(age-keygen -y $secret)
#  echo "Generating and encrypting SSH keys for $host..."
#
#  install -d -m755 $temp/etc/ssh
#  ssh-keygen -Af $temp
#  echo "Generated keys ..."
#  [ -d $key ] || mkdir -p $key
#  tar -cz -C $temp etc | age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age
#
#  echo "Keys encrypted and saved as ${key}/${flake}_sshkeys.tgz.age"
#  echo ""
#  echo "You can use these keys for decrypting secrets with agenix/sopsnix"
#  echo "Use the host key to sign all secrets:"
#  echo "$(cat $temp/etc/ssh/ssh_host_ed25519_key.pub)"
#  echo ""
#  echo "Cleaning $temp ..."
#  rm -rf $temp
#  echo "Done generating $flake keys"
#}
#
#rekey_keys() {
#  local flake="$1"
#  local secret="$2"
#  local key="$3" # where the ssh_host_keys will go
#  local oldkey="$4" # -k defines the old key to re-key with
#  local temp=$(mktemp -d)
#  public_key=$(age-keygen -y $secret)
#  echo "de-crypting SSH keys with old key for $hostname..."
#  age -d -i $oldkey ${key}/${flake}_sshkeys.tgz.age | tar -xz -C "$temp"
#  echo "re-encrypting SSH keys with new key for $hostname..."
#  tar -cz -C $temp etc |age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age
#  echo ""
#  echo "Cleaning $temp ..."
#  rm -rf $temp
#  echo "Done rekeying $flake keys"
#}
#
#deploy() {
#  local flake="$1"
#  local hostname="$2"
#  local secret="$3"
#  local key="$4" # where the ssh_host_keys are located
#  local temp=$(mktemp -d)
#
#  echo "Deploying $flake to $hostname..."
#  mkdir -p "$temp"
#  age -d -i $secret ${key}/${flake}_sshkeys.tgz.age | tar -xz -C "$temp"
#
#  # Run nixos-anywhere
#  nixos-anywhere ${options} -f .\#$flake --target-host $hostname --extra-files $temp
#  echo "Cleaning $temp ..."
#  rm -rf $temp
#  echo "Finished deploying $flake"
#}
#
#sshrun() {
#  local hostname="$1"
#  local sshcmd="$2"
#  local secret="$3"
#  ssh $hostname -i $secret $sshcmd
#}
#
#rebuild() {
#  local flake="$1"
#  local hostname="$2"
#  local action="$3"
#  local user="${hostname%@*}"
#  [[ ! "$user" == "root" ]] && { sudocmd=" --use-remote-sudo"; } || { sudocmd=""; }
#  echo "Rebuilding $flake to $hostname..."
#  nixos-rebuild "$action" --flake .\#"$flake" "${options}" --target-host "$hostname" "$sudocmd"
#}
