#!/usr/bin/env bash

###############################################################
### Initial Variables #########################################
###############################################################

RED='\033[0;31m'
GREEN='\033[0;32m'
#YELLOW='\033[0;33m'
CLEAR='\033[0m'

###############################################################
### Help Dialog ###############################################
###############################################################

# Normalize
set -eo pipefail
exe_root=$(pwd) # Where we are executing from
git_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd) # where we will be for most things

allargs=":hdk:c:"

show_help() {
  echo -e "
  $(printf '=%.0s' $(seq 1 "$(tput cols)"))
   ${GREEN}
            
            placeholder
            
            
            
   ${CLEAR}
  $(printf '=%.0s' $(seq 1 "$(tput cols)"))
  Usage:${RED} $0 ${GREEN}mode [options] [name]

    Options:
   ${RED}      [mode]           ${GREEN}  Specifies the operation you want to take.
   ${RED}
   ${RED}                       ${GREEN}    ls        =  List the nixosConfigurations in your flake and show their parameters.
   ${RED}                       ${GREEN}    genkey    =  Create new ssh keys to bootstrap a server
   ${RED}                       ${GREEN}    rekey     =  Decrypt and re-key the secrets/sshkeys
   ${RED}                       ${GREEN}    deploy    =  Run nixos-anywhere and deploy the server, destroying any and all data there.
   ${RED}                       ${GREEN}    test      =  Run nixos-rebuild test
   ${RED}                       ${GREEN}    boot      =  Run nixos-rebuild boot
   ${RED}                       ${GREEN}    switch    =  Run nixos-rebuild switch
   ${RED}                       ${GREEN}    ssh       =  Run arbitrary commands on remote servers
   ${RED}
   ${RED}      [name]           ${GREEN}  The name of the nixosConfiguration you want to work with
   ${RED}
   ${RED}   -h | --help         ${GREEN}  Display help dialog (You can specify the mode as well)
   ${RED}   -d | --debug        ${GREEN}  Show debug messages
   ${CLEAR}
  $(printf '=%.0s' $(seq 1 "$(tput cols)"))" | less

}

###############################################################
### helper funcs ##############################################
###############################################################

split_args() {

  pos_args=()
  flag_args=()

  while [[ $# -gt 0 ]]; do
    case "$1" in
      -k|-c) # consuming args
        flag_args+=("$1" "$2")
        shift 1 # FIXED: This bug is caused when shift 2: a consuming arg with no provided arg will loop forever
        shift 1
        ;;
      -*)
        flag_args+=("$1")
        shift
        ;;
      *)
        pos_args+=("$1")
        shift
        ;;
    esac
  done
}

###############################################################
### main ######################################################
###############################################################

main() {

  split_args "$@"
  set -- "${flag_args[@]}"

  while getopts $allargs opt; do
    case $opt in
      d) debug="1" ;;
      *) : ;;
    esac
  done
  OPTIND=1
  [ "$debug" ] && echo "Debug Enabled"

  set -- "${pos_args[@]}"

  mode=$1

  case "$mode" in
    "ls")
      shift
      ls-mode "$@" && exit 0
    ;;
    "genkey")
      shift
      genkey-mode "$@" && exit 0
    ;;
    "rekey")
      shift
      rekey-mode "$@" && exit 0
    ;;
    "deploy")
      shift
      deploy-mode "$@" && exit 0
    ;;
    "test")
      shift
      test-mode "$@" && exit 0
    ;;
    "boot")
      shift
      boot-mode "$@" && exit 0
    ;;
    "switch")
      shift
      switch-mode "$@" && exit 0
    ;;
    "ssh")
      shift
      ssh-mode "$@" && exit 0
    ;;
    *)
      show_help && exit 1;
    ;;

  esac
}

###############################################################
### modes #####################################################
###############################################################
ls-mode() {

  [ "$debug" ] && echo "lsmode entered"
  set -- "${flag_args[@]}"

  [ "$debug" ] && echo "Flags set:" "$@"

  while getopts $allargs opt; do
    case $opt in
      h)
        echo -e "Usage:"
        echo -e "    ${RED}depnix ls${GREEN} [options] [<nixosConfiguration...>]${CLEAR}"
        echo -e "Options:"
        echo -e "    -h | --help"
        exit 0 ;;
      *) : ;;
    esac
  done
  OPTIND=1
  [ "$debug" ] && echo "Opts parsed"

  set -- "${pos_args[@]}" && shift
  [ "$debug" ] && echo "Positional args set:" "$@"

  nixosNames=$(nix eval .#nixosConfigurations --apply 'builtins.attrNames')
  [ "$debug" ] && echo "nixosNames parsed:" "$nixosNames"
  if [ $# -lt 1 ]; then
    [ "$debug" ] && echo "No nixos systems chosen, checking all"
    set -- "$(nix eval .#nixosConfigurations --apply 'builtins.attrNames'|jq -r '.[]')"
  fi
  while [ $# -gt 0 ]; do
    [ "$debug" ] && echo "$# nixos systems left:" "$@"
    if "$(echo "$nixosNames" | jq "IN(.[]; \"$1\")")"; then
      Conf=$(nix eval --json ".#nixosConfigurations.$1.config.depnix" |jq)
      echo "nixosConfiguration.$1.depnix = $Conf"
    else
      echo -e "$1 is not a valid nixosConfiguration"
    fi
    shift
    [ "$debug" ] && echo "Shifted args"
  done

}

genkey-mode() {

  [ "$debug" ] && echo "genkey entered"
  set -- "${flag_args[@]}"
  [ "$debug" ] && echo "Flag Args set:" "$@"

  while getopts $allargs opt; do
    case $opt in
      h)
        echo -e "Usage:"
        echo -e "    ${RED}depnix genkey${GREEN} [options] <nixosConfiguration> </path/to/ssh/host/key/store>${CLEAR}"
        echo -e "Options:"
        echo -e "    -h | --help    Show help dialog"
        exit 0 ;;
      *) : ;;
    esac
  done
  OPTIND=1
  [ "$debug" ] && echo "getopts parsed:" "$@"

  set -- "${pos_args[@]}" && shift
  [ "$debug" ] && echo "Postitional Args set:" "$@"

  if [ $# -lt 2 ]; then
    echo "Not enough arguments. See help with: depnix genkey -h"
    exit 1
  elif [ $# -gt 2 ]; then
    echo "Too many arguments. See help with: depnix genkey -h"
    exit 1
  fi

  [ "$debug" ] && echo "Checks passed"

  flakename="$1"
  keydir="$2"
  keyfile="$keydir/${flakename}_sshhostkeys.tgz.enc"

  [ "$debug" ] && echo "Values set:" "flakename: $flakename" "keydir: $keydir" "keyfile: $keyfile"

  [ -z "$keydir" ] && echo "No keydirectory specified. See help with depnix genkey -h" && exit 1

  if [ -f "$keyfile" ]; then
    gum confirm --default=no --prompt.foreground="#69CC5C" --selected.background="#69CC5C" --selected.foreground="235" \
    "Keys ($keyfile) already exists are you sure you want to overwrite?" || exit 0
  fi

  nixosNames=$(nix eval .#nixosConfigurations --apply 'builtins.attrNames')
  if ! "$(echo "$nixosNames" | jq "IN(.[]; \"$flakename\")")"; then
    echo "$flakename is not a nixosConfiguration"
    exit 1
  fi
  [ "$debug" ] && echo "nixos found"

  deploy=$(nix eval .#nixosConfigurations."$flakename".config.depnix.deploy --json|jq -r )
  [ "$debug" ] && echo "Deploy: $deploy"
  temp=$(mktemp -d)
  [ "$debug" ] && echo "temp: $temp"
  encryptionKey=$(jq -r '.encryptionKey' <<< "$deploy" )
  [ "$debug" ] && echo "encryptionKey: $encryptionKey"
  echo "Generating and encrypting SSH keys for $flakename..."

  install -d -m755 "$temp/etc/ssh"
  ssh-keygen -Af "$temp"
  [ "$debug" ] && echo "sshkeys made:"
  [ "$debug" ] && ls -lhA "$temp/etc/ssh"
  echo "Generated keys ..."
  [ -d "$keydir" ] || mkdir -p "$keydir"
  tar -cz -C "$temp" etc | age -e -o "$keyfile" -r "$encryptionKey"
  awk  '{print $1 " " $2}' <<< "$(cat "$temp/etc/ssh/ssh_host_ed25519_key.pub")" > "$keyfile.pub"

  echo "Keys encrypted and saved here: $keyfile"
  echo ""
  echo "You can use this key for decrypting secrets with agenix/sopsnix"
  echo "Use the host key to encrypt all secrets this host needs:"
  awk  '{print $1 " " $2}' <<< "$(cat "$temp/etc/ssh/ssh_host_ed25519_key.pub")"
  echo ""
  rm -rf "$temp"
  [ "$debug" ] && echo "temp directory cleaned"
}

rekey-mode() {

  [ "$debug" ] && echo "rekey entered"
  set -- "${flag_args[@]}"
  [ "$debug" ] && echo "Flag Args set:" "$@"

  while getopts $allargs opt; do
    case $opt in
      h)
        echo -e "Usage:"
        echo -e "    ${RED}depnix rekey${GREEN} [options] <nixosConfiguration> </path/to/ssh/host/key/store>${CLEAR}"
        echo -e "Options:"
        echo -e "    -h | --help"
        echo -e "    -k | --key /path/to/old/private/key"
        exit 0
        ;;
      k)
        oldkey="$OPTARG"
        [ "$debug" ] && echo "oldkey set"
        ;;
    esac
  done
  OPTIND=1
  [ "$debug" ] && echo "getopts parsed:" "$@"

  [ -z "$oldkey" ] && echo "No old key specified, we need one to decrypt the keys prior to re-keying. See help with depnix rekey -h" && exit 1
  if ! [ -f "$oldkey" ]; then echo "The old key doesn't seem to exist, check the folder for the file"; exit 1; fi

  set -- "${pos_args[@]}" && shift
  [ "$debug" ] && echo "Postitional Args set:" "$@"

  if [ $# -lt 2 ]; then
    echo "Not enough arguments. See help with: depnix genkey -h"
    exit 1
  elif [ $# -gt 2 ]; then
    echo "Too many arguments. See help with: depnix genkey -h"
    exit 1
  fi

  [ "$debug" ] && echo "Checks passed"

  flakename="$1"
  keydir="$2"
  keyfile="$keydir/${flakename}_sshhostkeys.tgz.enc"

  [ "$debug" ] && echo "Values set:" "flakename: $flakename" "keydir: $keydir" "keyfile: $keyfile"

  [ -z "$keydir" ] && echo "No keydirectory specified. See help with depnix genkey -h" && exit 1
  if ! [ -f "$keyfile" ]; then
    echo "The folder $keydir doesn't contain the file: ${flakename}_sshhostkeys.tgz.enc"
    exit 1
  fi

  nixosNames=$(nix eval .#nixosConfigurations --apply 'builtins.attrNames')
  if ! "$(echo "$nixosNames" | jq "IN(.[]; \"$flakename\")")"; then
    echo "$flakename is not a nixosConfiguration"
    exit 1
  fi
  [ "$debug" ] && echo "nixos found"

  deploy=$(nix eval .#nixosConfigurations."$flakename".config.depnix.deploy --json|jq -r )
  [ "$debug" ] && echo "Deploy: $deploy"
  temp=$(mktemp -d)
  [ "$debug" ] && echo "temp: $temp"
  encryptionKey=$(jq -r '.encryptionKey' <<< "$deploy" )
  [ "$debug" ] && echo "encryptionKey: $encryptionKey"
  echo "decrypting and re-encrypting SSH keys for $flakename..."

  age -d -i "$oldkey" -o - "$keyfile" | tar -C "$temp" -xz
  [ "$debug" ] && echo "Keys decrypted"
  [ "$debug" ] && ls -lhA "$temp/etc/ssh"
  tar -cz -C "$temp" etc | age -e -o "$keyfile" -r "$encryptionKey"
  awk  '{print $1 " " $2}' <<< "$(cat "$temp/etc/ssh/ssh_host_ed25519_key.pub")" > "$keyfile.pub"

  echo "Keys re-encrypted and saved here: $keydir/${flakename}_sshhostkeys.tgz.enc"
  echo ""
  echo "You can use this key for decrypting secrets with agenix/sopsnix"
  echo "Use the host key to encrypt all secrets this host needs:"
  awk  '{print $1 " " $2}' <<< "$(cat "$temp/etc/ssh/ssh_host_ed25519_key.pub")"
  echo ""
  rm -rf "$temp"
  [ "$debug" ] && echo "temp directory cleaned"

}
main "$@"

#  while getopts ":hk:c:" opt; do
#    case $opt in
#      k) oldkey="$OPTARG" ;;
#      c) sshcmd="$OPTARG" ;;
#      :) show_help && exit 1 ;;
#      \?) show_help && exit 1 ;;
#    esac
#  done
#
#  [[ $action == "ssh" && $sshcmd == 0 ]] && (echo "No command given for ssh mode" && exit 1)
#
#  case $action in
#    "init") init ;;
#    "dryrun") [[ $original_action == "init" ]] && dryinit || [[ "$original_action" =~ ^(genkey|rekey|deploy)$ ]] && jsonroot="deploy" || jsonroot="rebuild" ;;
#    "genkey"|"rekey"|"deploy") jsonroot="deploy" ;;
#    "switch"|"test"|"boot"|"ssh") jsonroot="rebuild" ;;
#    *) echo "Invalid action: $action" && echo "" && show_help && exit 1 ;;
#  esac
#
#  servers=$(nix eval --json '.#nixosConfigurations' --apply 'builtins.attrNames')
#  server_keys=$( nix eval --file "$nix_file" --json | jq keys )
#
#  echo "$server_configs" | jq -c '.[]' | while read -r jsonroot; do
#
#    hostname=$(echo "$jsonroot" | jq -r '.hostname')
#    secret=$(echo "$jsonroot" | jq -r '.secret')
#    key=$(echo "$jsonroot" | jq -r '.keydir')
#
#    echo "performing $action on $flake ==================================="
#    case $action in
#      "ssh") sshrun "$hostname" "$sshcmd" "$secret" ;;
#      "dryrun") dryrun "$original_action" "$flake" "$hostname" "$secret" "$key" "$oldkey" ;;
#      "genkey") generate_keys "$flake" "$hostname" "$secret" "$key" ;;
#      "rekey") rekey_keys "$flake" "$secret" "$key" "$oldkey" ;;
#      "deploy") deploy "$flake" "$hostname" "$secret" "$key" ;;
#      "switch"|"test"|"boot") rebuild "$flake" "$hostname" "$action" ;;
#      *) echo "Invalid action: $action" && echo "" && show_help && exit 1 ;;
#    esac
#    echo ""
#    echo "================================================================"
#
#  done
#}
#
#main "$@"
 #${RED}                       ${GREEN}    ls        =  List the nixosConfigurations in your flake and show their parameters.
 #${RED}                       ${GREEN}    genkey    =  Create new ssh keys to bootstrap a server
 #${RED}                       ${GREEN}    rekey     =  Decrypt and re-key the secrets/sshkeys
 #${RED}                       ${GREEN}    deploy    =  Run nixos-anywhere and deploy the server, destroying any and all data there.
 #${RED}                       ${GREEN}    test      =  Run nixos-rebuild test
 #${RED}                       ${GREEN}    boot      =  Run nixos-rebuild boot
 #${RED}                       ${GREEN}    switch    =  Run nixos-rebuild switch
 #${RED}                       ${GREEN}    ssh       =  Run arbitrary commands on remote servers
# ${RED}   -c | --command      ${GREEN}  when using ssh mode, specify a command to run on the servers
# ${RED}                       ${GREEN}  this option uses ssher: https://github.com/kr-nn/ssher
# ${RED}
# ${RED}   -o | --options      ${GREEN}  Add arbitrary options to nixos-rebuild/nixos-anywhere/ssher
# ${RED}
# ${RED}   -k | --key          ${GREEN}  Path to current key when using rekey mode
# ${RED}
# ${RED}   -d | --debug        ${GREEN}  Explain what we are going to do instead of doing it
# ${RED}

#generate_keys() {
#  local flake="$1" # Needs to be in each function because we don't want to share a directory with multiple servers
#  local hostname="$2"
#  local secret="$3"
#  local key="$4" # where the ssh_host_keys will go
#  local temp=$(mktemp -d)
#  local host="${hostname#*@}"
#  public_key=$(age-keygen -y $secret)
#  echo "Generating and encrypting SSH keys for $host..."
#
#  install -d -m755 $temp/etc/ssh
#  ssh-keygen -Af $temp
#  echo "Generated keys ..."
#  [ -d $key ] || mkdir -p $key
#  tar -cz -C $temp etc | age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age
#
#  echo "Keys encrypted and saved as ${key}/${flake}_sshkeys.tgz.age"
#  echo ""
#  echo "You can use these keys for decrypting secrets with agenix/sopsnix"
#  echo "Use the host key to sign all secrets:"
#  echo "$(cat $temp/etc/ssh/ssh_host_ed25519_key.pub)"
#  echo ""
#  echo "Cleaning $temp ..."
#  rm -rf $temp
#  echo "Done generating $flake keys"
#}
#
#rekey_keys() {
#  local flake="$1"
#  local secret="$2"
#  local key="$3" # where the ssh_host_keys will go
#  local oldkey="$4" # -k defines the old key to re-key with
#  local temp=$(mktemp -d)
#  public_key=$(age-keygen -y $secret)
#  echo "de-crypting SSH keys with old key for $hostname..."
#  age -d -i $oldkey ${key}/${flake}_sshkeys.tgz.age | tar -xz -C "$temp"
#  echo "re-encrypting SSH keys with new key for $hostname..."
#  tar -cz -C $temp etc |age -e -r $public_key > ${key}/${flake}_sshkeys.tgz.age
#  echo ""
#  echo "Cleaning $temp ..."
#  rm -rf $temp
#  echo "Done rekeying $flake keys"
#}
#
#deploy() {
#  local flake="$1"
#  local hostname="$2"
#  local secret="$3"
#  local key="$4" # where the ssh_host_keys are located
#  local temp=$(mktemp -d)
#
#  echo "Deploying $flake to $hostname..."
#  mkdir -p "$temp"
#  age -d -i $secret ${key}/${flake}_sshkeys.tgz.age | tar -xz -C "$temp"
#
#  # Run nixos-anywhere
#  nixos-anywhere ${options} -f .\#$flake --target-host $hostname --extra-files $temp
#  echo "Cleaning $temp ..."
#  rm -rf $temp
#  echo "Finished deploying $flake"
#}
#
#sshrun() {
#  local hostname="$1"
#  local sshcmd="$2"
#  local secret="$3"
#  ssh $hostname -i $secret $sshcmd
#}
#
#rebuild() {
#  local flake="$1"
#  local hostname="$2"
#  local action="$3"
#  local user="${hostname%@*}"
#  [[ ! "$user" == "root" ]] && { sudocmd=" --use-remote-sudo"; } || { sudocmd=""; }
#  echo "Rebuilding $flake to $hostname..."
#  nixos-rebuild "$action" --flake .\#"$flake" "${options}" --target-host "$hostname" "$sudocmd"
#}
